### ISSUE TITLE
If you enlarge/shrink window the canvas will stay the same size

### ISSUE THREAD

**Issue by Kert** [Flashfyre/Yume-2kki-Explorer#10]

**Comment by Flashfyre** [comment]
I have tried to fix this but to no avail. Nothing seems to reset the canvas. If you want to take a crack at it go ahead but I don't think it's that big of a deal to fix myself.

**Comment by Kert** [comment]
Looks like it's force-graph bug

**Comment by Flashfyre** [comment]
Then I'll try to keep a lookout for a fix on it if they release one. Closing this for now.
